version: '3.4'

services:
  app:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: todo-app
    ports:
      - '${APP_PORT}:${APP_PORT}'
    command: npm run start:dev
    restart: 'on-failure'
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/src/app

  postgres:
    image: postgres:latest
    volumes:
      - db:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: todo_app
    ports:
      - "5432:5432"

volumes:
  db:
